---
- name: Create cache directory
  become: true
  file:
    path: "{{ docker_aws_ecr_proxy_cache_path  }}"
    state: directory
    mode: "u=rwx,go=rx"
    recurse: true

- name: Copy the ssl certificates
  become: true
  copy:
    src: "{{ item }}"
    dest: "{{ docker_aws_ecr_proxy_ssl_host_path }}/{{ item }}"
  with_items:
    - certificate.pem
    - key.pem
  when:
    - docker_aws_ecr_proxy_ssl_enabled | bool
    - docker_aws_ecr_proxy_ssl_copy_certs | bool

- name: Print current cache directory size information
  become: true
  command: du -hs {{ docker_aws_ecr_proxy_cache_path  }}  # noqa 301
  changed_when: false
  check_mode: false

- name: Pull image
  become: true
  docker_image:
    name: "{{ docker_aws_ecr_proxy_image }}"
    source: "pull"
  register: _image_pull
  when: docker_aws_ecr_proxy_pull|bool
  tags:
    - pull-image

- name: Remove previous proxy container
  become: true
  docker_container:
    name: docker-registry-proxy
    state: absent
  when: docker_aws_ecr_proxy_clear_cache|bool

- name: Clear local cache
  become: true
  file:
    path: "{{ docker_aws_ecr_proxy_cache_path }}"
    state: absent
  when: docker_aws_ecr_proxy_clear_cache|bool

- name: Run new docker registry proxy container
  become: true
  docker_container:
    image: "{{ docker_aws_ecr_proxy_image }}"
    name: "{{ docker_aws_ecr_proxy_name | default(omit) }}"
    network_mode: host
    restart_policy: unless-stopped
    recreate: "{{ (docker_aws_ecr_proxy_clear_cache|bool) or (_image_pull is defined and _image_pull is changed) }}"
    dns_servers: "{{ docker_aws_ecr_proxy_backend_resolvers | default(omit) }}"
    state: started
    tmpfs:
      - "/tmp"
    env: >
      {{
        {
          "RESOLVER": docker_aws_ecr_proxy_backend_resolvers | default(['127.0.0.1:53']) | join(' '),
          "PORT": "{{ docker_aws_ecr_proxy_port }}",
          "UPSTREAM": docker_aws_ecr_proxy_backend_schema ~ "//" ~ docker_aws_ecr_proxy_backend,
          "CACHE_MAX_SIZE": docker_aws_ecr_proxy_cache_limit,
          "AWS_REGION": docker_aws_ecr_proxy_region,
          "ENABLE_SSL": "true" if (docker_aws_ecr_proxy_ssl_enabled | bool) else "false"
        }
        | combine({
          "AWS_PROFILE": docker_aws_ecr_proxy_profile
        } if (docker_aws_ecr_proxy_profile|length) else {
          "AWS_ACCESS_KEY_ID": docker_aws_ecr_proxy_access_id,
          "AWS_SECRET_ACCESS_KEY": docker_aws_ecr_proxy_secret_key
        })
        | combine({
          "REGISTRY_HTTP_TLS_KEY": docker_aws_ecr_proxy_ssl_container_path ~ "/key.pem",
          "REGISTRY_HTTP_TLS_CERTIFICATE": docker_aws_ecr_proxy_ssl_container_path ~ "/certificate.pem"
        } if (docker_aws_ecr_proxy_ssl_enabled | bool) else {})
      }}
    volumes: >
      {{
        [
          docker_aws_ecr_proxy_cache_path ~ ":/cache:rw"
        ] | union([
          docker_aws_ecr_proxy_profile_path ~ ":/root/.aws:ro"
        ] if (docker_aws_ecr_proxy_profile_path|length) else [])
        | union([
          docker_aws_ecr_proxy_ssl_host_path ~ "/" ~ docker_aws_ecr_proxy_ssl_host_cert_name
            ~ ":" ~ docker_aws_ecr_proxy_ssl_container_path ~ "/certificate.pem:ro",
          docker_aws_ecr_proxy_ssl_host_path ~ "/" ~ docker_aws_ecr_proxy_ssl_host_key_name
            ~ ":" ~ docker_aws_ecr_proxy_ssl_container_path ~ "/key.pem:ro"
        ] if (docker_aws_ecr_proxy_ssl_enabled | bool) else [])
      }}
